### ISSUE TITLE
tern_for_sublime doesn't fully work (ecma5, browser, jquery)

### ISSUE THREAD

**Issue by dave8401** [marijnh/tern_for_sublime#54]
After the install I can't get e.g. browser support to work. These examples do not work:

	document.body.
	// -> completion (e.g. addEventListener) does not work

	$("form").on("click", selector, data, function(e) {
		// -> completion (e.g. event functions) does not work
	});

**Comment by subhaze** [comment]
On my end I can confirm that `document.body.` is giving correct completions.

As for the fn signature `on("click", selector, data, function(e)` does not give completions for `e`, but `on("click", function(e)` does.

**Comment by N4M3Z** [comment]
This might be obvious, but since I was the one having the issue, I might as well make the point: `tern` autocompletes only on packages installed through `npm`, hence you won't get autocompletion for `document` unless you installed `npm install browser`. I hope this does save somebody's time some day.
